# Generated by Django 3.2 on 2021-04-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robota',
            name='dzialki',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='jew',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='obiekt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='obr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='obszar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='powiat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='robota',
            name='idpracy',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='robota',
            name='wojew',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
