# Generated by Django 3.2.5 on 2021-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0002_auto_20210430_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spis',
            name='pozycja',
        ),
        migrations.AlterField(
            model_name='robota',
            name='data_operat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='robota',
            name='idpracy',
            field=models.CharField(default='XX.6640.XXXX.RRRR', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='robota',
            name='obiekt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
