# Generated by Django 3.2.5 on 2021-08-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0004_auto_20210805_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='robota',
            name='data_aktu',
            field=models.CharField(default='RRRR-MM-DD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='data_mat',
            field=models.CharField(default='RRRR-MM-DD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='status',
            field=models.CharField(default='w trakcie', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='zmianaBDOT',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='zmianaEGIB',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='robota',
            name='zmianaGESUT',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='dokZamawiajacy',
            field=models.TextField(default='Dla zamawiającego przygotowano...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='egibzmiany',
            field=models.TextField(default='Kierownik prac stwierdził/nie stwierdził ...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='granice',
            field=models.TextField(default='Granice spełniają/nie spełniają ...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='techMet3',
            field=models.TextField(default='Wykonano pomiar kontrolny ...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='techMet4',
            field=models.TextField(default='Wykonano pomiar systuacyjny metodą ...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='techMet5',
            field=models.TextField(default='Wyniki uzyskano w układzie ...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='zasilenie',
            field=models.TextField(default='Przekazno pliki w formacie ...'),
        ),
        migrations.AddField(
            model_name='sprawozdanie',
            name='zudpozwolenie',
            field=models.TextField(default='ZUD i pozwolenie na budowe ..'),
        ),
        migrations.AlterField(
            model_name='sprawozdanie',
            name='techMet1',
            field=models.TextField(default='Wykonano porównanie... '),
        ),
        migrations.AlterField(
            model_name='sprawozdanie',
            name='techMet2',
            field=models.TextField(default='Założono osnowę pomiarową ...'),
        ),
        migrations.CreateModel(
            name='WykazWspPom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wykazpom', models.TextField(default='Wykaz współrzędnych punktów pomierzonych ')),
                ('idpracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.robota')),
            ],
        ),
        migrations.CreateModel(
            name='WykazWspOsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wykaz', models.TextField(default='Wykaz wsp')),
                ('idpracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.robota')),
            ],
        ),
        migrations.CreateModel(
            name='SzkicPolowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szkicpolPDF', models.FileField(upload_to='temp/')),
                ('idpracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.robota')),
            ],
        ),
        migrations.CreateModel(
            name='SzkicOsnowyPom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szkicPDF', models.FileField(upload_to='temp/')),
                ('idpracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.robota')),
            ],
        ),
        migrations.CreateModel(
            name='MapaPorownania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpztPDF', models.FileField(upload_to='temp/')),
                ('idpracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.robota')),
            ],
        ),
        migrations.CreateModel(
            name='DaneObsOsnPom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raport', models.TextField(default='Wynik wyrównania/raport z pomiaru GPS ...')),
                ('idpracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operat.robota')),
            ],
        ),
    ]
