# Generated by Django 3.2.5 on 2021-09-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0005_auto_20210825_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daneobsosnpom',
            name='idpracy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
        migrations.AlterField(
            model_name='sprawozdanie',
            name='idpracy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
        migrations.AlterField(
            model_name='szkicosnowypom',
            name='idpracy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
        migrations.AlterField(
            model_name='szkicpolowy',
            name='idpracy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
        migrations.AlterField(
            model_name='wykazwsposn',
            name='idpracy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
        migrations.AlterField(
            model_name='wykazwsppom',
            name='idpracy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
    ]
