# Generated by Django 3.2.5 on 2022-01-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0007_auto_20210918_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapaporownania',
            name='idpracy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='operat.robota'),
        ),
    ]
